#   _______ _           _                 ______
#  |__   __(_)         | |               |___  /
#     | |   _ _ __ ___ | |__   ___ _ __     / /
#     | |  | | '_ ` _ \| '_ \ / _ \ '__|   / /
#     | |  | | | | | | | |_) |  __/ |     / /__
#     |_|  |_|_| |_| |_|_.__/ \___|_|    /_____|

# === COLOR CODES ===
# This plugin supports old color codes like: &c, &l, &o, etc.
# It also supports MiniMessage, a more advanced way to format messages:
# https://docs.advntr.dev/minimessage/format.html
# With MiniMessage, you can add HEX colors, gradients, hover and click events, etc.


# === GENERAL SETTINGS ===

# If set to true, TimberZ will check for updates and let you know if there's a newer version
checkForUpdates: true

# Set the language to any code found in the "lang" folder (don't add the .yml extension)
# You can add your own language files. Use https://github.com/ZetaPlugins/TimberZ/tree/main/src/main/resources/lang/en-US.yml as a template
# If you want to help translating the plugin, please refer to this article: https://docs.zetaplugins.com/#contributing
#  | en-US | de-DE | pl-PL | ru-RU |
lang: "en-US"

# The accent color of the plugin. This color replaces %ac% in the lang files.
accentColor: "<#00D26A>"


# === TIMBER SETTINGS ===

# Regardless of the settings below, you can disallow TimberZ for a specific player by disallowing them the "timberz.usetimber" permission.

# If set to true, players can enable or disable timber mode by pressing F with a qualifying axe in hand
toggleTimber: true

# If set to true, you can only use axes that have the "Timber" enchantment which can be applied like a normal Enchantment.
requireCustomEnchant: true

# If set to true, you can only use axes with a customModelData value in the list below
restrictAxeModelData: false

# If restrictAxeModelData is set to true, you can only use axes with a customModelData value in this list
allowedModelData:
  - 100

# If set to true, Leaves will decay instantly when cutting down a tree
instantLeafDecay: true

# If set to true, TimberZ will replant the tree after cutting it down
replant: true

# Modify how much durability is removed from the axe when cutting down a tree
# Formula: logCount * durabilityMultiplier
durabilityMultiplier: 1.0

# The minimum durability the axe must have after cutting down a tree
minDurability: 10

# If set to true, Players will need to use an axe (defined in the blocks.yml file) to use TimberZ
# When this is set to false, you can no longer toggle TimberZ by pressing F
requireAxeMaterial: true

# If set to true, you can insta mine leaves when the TimberZ conditions are met
instaBreakLeavesWithTimber: false

# Send a message to the player when they try to use timber mode in a WorldGuard region that does not allow it
messageOnRegionViolation: false

# If using AuraSkills, you can have a custom XP multiplier for the Foraging skill
# Example: If you set this to 2.0, players will receive double the XP for using TimberZ
# Example2: If you set this to 0.5, players will receive half the XP for using TimberZ
auraSkillsXPMultiplier: 1.0

# If using mcMMo, you can have a custom XP multiplier for the Tree feller skill
# Example: If you set this to 2.0, players will gain 2 XP for each log chopped with TimberZ
mcMMoXP: 1.0


# === TREE DETECTION ===

# Only change these settings if you know what you are doing!
# These are used to detect trees and their leaves and are already fine tuned.

leavesSearchRadius: 4
maxTreeSize: 500
maxSearchRadius: 1
diagonalSearchRange: 2
minLeavesRequired: 5
minLogsRequired: 3