name: TimberZ
version: '${version}'
main: com.zetaplugins.timberz.TimberZ
bootstrapper: com.zetaplugins.timberz.bootstrap.TimberZBootstrap
api-version: '1.21'
load: POSTWORLD
authors: [ ZetaPlugins ]
website: https://zetaplugins.com/
description: The Ultimate Timber and Lumberjack axe plugin!

dependencies:
    server:
        WorldGuard:
            load: BEFORE
            required: false
            join-classpath: true
        PlaceholderAPI:
            load: BEFORE
            required: false
            join-classpath: true
        AuraSkills:
            load: BEFORE
            required: false
            join-classpath: true
        mcMMO:
            load: BEFORE
            required: false
            join-classpath: true

permissions:
    timberz.admin:
        default: op
        description: Allows the user to manage the plugin
    timberz.usetimber:
        default: true
        description: Allows the user to use the TimberZ feature